{% set version = "8.4.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-delaporte
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/Delaporte_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/Delaporte/Delaporte_{{ version }}.tar.gz
  sha256: 9b80ce53cbb7a4cf5d08a14a75b80db3c7006f20d0ef29372950971e849660bf

build:
  # Checking windows to see if it passes. Uncomment the line if it fails.
  # skip: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}        # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem            # [win]
    - {{ posix }}make
    - {{ posix }}sed                   # [win]
    - {{ posix }}coreutils             # [win]
    - {{ posix }}zip                   # [win]
    - llvm-openmp                      # [osx]
    - libgomp                          # [linux]
  host:
    - libblas
    - liblapack
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('Delaporte')"           # [not win]
    - "\"%R%\" -e \"library('Delaporte')\""  # [win]

about:
  home: https://github.com/aadler/Delaporte
  license: BSD-2-Clause
  summary: Provides probability mass, distribution, quantile, random-variate generation, and method-of-moments parameter-estimation functions for the Delaporte distribution. The Delaporte is a discrete probability distribution which can be considered the convolution of a negative binomial distribution with a Poisson distribution.
    Alternatively, it can be considered a counting distribution with both Poisson and negative binomial components. It has been studied in actuarial science as a frequency distribution which has more variability than the Poisson, but less than the negative binomial.
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_2_clause
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Date/Publication: 2019-05-17 20:50:24 UTC
